apiVersion: v1
kind: Secret
metadata:
  name: livekit-secrets
  namespace: livekit
type: Opaque
stringData:
  url: "ws://livekit-service.livekit.svc.cluster.local:7880"
  api-key: "devkey-livekit-api-key-2024"
  api-secret: "devkey-livekit-api-secret-2024-min-32-chars"


