apiVersion: v1
kind: Service
metadata:
  name: livekit-service
  namespace: livekit
  labels:
    app: livekit-server
spec:
  type: ClusterIP
  ports:
  - port: 7880
    targetPort: 7880
    protocol: TCP
    name: http
  - port: 7881
    targetPort: 7881
    protocol: TCP
    name: tcp
  selector:
    app: livekit-server


